config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'items' => 'item#index', as: :items
  get 'items/new' => 'item#new', as: :new_item
  get 'items/:id' => 'item#show', as: :item
  post 'items' => 'item#create', as: :create_item
  delete 'items/:id' => 'item#destroy', as: :destroy_item
  post 'items/:id/toggle' => 'item#toggle', as: :toggle_item
  get 'items/:id/edit' => 'item#show', as: :edit_item
  patch 'items/:id/edit' => 'item#show', as: :save_item
  get 'items/:id/up' => 'item#move_up', as: :move_item_up
  get 'items/:id/down' => 'item#move_down', as: :move_item_down

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/item.rb
class Item
  include MongoMapper::Document

  # 33554432 is the closest power of two to intMax/30, We're assuming most lists are 30 items or fewer, so using this
  # number reduces the number of resorts we have to make, which require writing to every item in the list.
  @@increment = 33554432 
  #Ruby automatically converts integers to a large integer class when they overflow, so there's (practically) no limit
  # to how big they can be. We'll define a max here so we don't run into issues with Swift
  @@intMax = 2147483647 

  key :title, String
  key :done, Boolean
  key :parent, String
  key :order, Integer
  key :duedate, DateTime
  key :user_id, String
  key :notes, String

  def children
    #TODO: cache this
    child_items = Item.where(:parent => id.to_s).order(:order).all
  end

  def insert_tail(item)
    if children.count == 0 
      item.order = @@increment
    elsif children.last.order + @@increment < @@intMax
      item.order = children.last.order + @@increment
    else
      #reorder_list will return the increment used to equally distribute the items
      #item hasn't yet been saved, so it won't show up in children.count
      item.order = reorder_list * (children.count+1)
    end
    item.save
  end

  def insert_head(item)
    if children.count == 0
      item.order = @@increment
    elsif children.first.order/2 < 2
      item.order = children.first.order/2
    else
      item.order = 0
      #reorder_list will return the increment used to equally distribute the items
      item.order = reorder_list/2
    end
    item.save
  end

  def insert_after(after, item)
    if children.index(after) < children.count-1
      np2 = children[children.index(after)+1]
      np1 = children[children.index(after)]

      if (np2.order-np1.order)/2 > 2
        item.order = (np2.order-np1.order)/2 + np1.order
        item.save
      else
        item.order = np1.order + 1
        item.save
        reorder_list
      end

    else
      insert_tail(item)
    end
  end

  def insert_before(before, item)
    if children.index(before) >= 1
      nm2 = children[children.index(before)-1]
      nm1 = children[children.index(before)]

      if (nm1.order-nm2.order)/2 > 2
        item.order = (nm1.order-nm2.order)/2 + nm2.order
        item.save
      else
        item.order = nm1.order - 1
        item.save
        reorder_list
      end
    else
      insert_head(item)
    end
  end

  def reorder_list
    #check if we can just redistribute everything based on our standard increment
    
    children.count * @@increment < @@intMax ? 
      new_increment = @@increment : 
      new_increment = @@intMax/(children.count+1)

    order_val = 1
      children.each do |i|
        i.order = new_increment * order_val
        i.save
        order_val += 1
      end
    new_increment
  end

end

app/controllers/item_controller.rb
class ItemController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :check_authN
  before_action :set_item, only: [:show, :update, :move_up, :move_down, :toggle, :edit, :update, :destroy]
  before_action :check_authZ, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.where(:user_id => current_user.id.to_s, :parent => nil)
    respond_to do |format|
      format.html
      format.json
    end
  end

  #GET /lists/1
  def show
    #fix up existing lists, so they can be reordered if they don't have an existing order value
    @item.reorder_list if @item.children.any?{|i| i.order.nil? }

      respond_to do |format|
        format.html
        format.json 
          @json = { :item => @item, :children => @item.children }.to_json
      end
  end


  def toggle
    respond_to do |format|
      @item.done = params[:done] == 'true'
      if @item.save
        format.html { render :results => 'Item saved.' }
        format.js { render :data => "we good!", :status => :ok }
      else
        format.html { render :action => "new" }
        format.json
      end
    end
  end

  def update
    respond_to do |format|
      @item.done = params[item.id.to_s] == 'true'
      if @item.save
        format.html { redirect_to(@item, :notice => 'Item saved.') }
        format.js
      else
        format.html { render :action => "new" }
        format.js
      end
    end
  end

  # new.html.erb
  def new
    @item = Item.new
    respond_to do |format|
      format.html
    end
  end

  def create
    #TODO, check if we're over the max number of supported items per list.
    #very unlikely, considering we're supporting Int32Max
    @item = Item.new(params.require(:item).permit(:title, :parent))
    @item.user_id = current_user.id
    respond_to do |format|
      if @item.parent
        if Item.find(@item.parent).insert_tail(@item)
          #redirect to parent list
          format.html { redirect_to Item.find(@item.parent)}
        else
          format.html { render action: "new", notice: 'There was a problem creating the item, please try again.' }
        end
      else
        if @item.save
          format.html { redirect_to @item, notice: "List was successfully created, start adding items!" }
        else
          format.html { render action: "new" }
        end
      end
    end
  end

  def move_up
    parent = Item.find(@item.parent)

    if parent.children.index(@item) >= 1
      before = parent.children[parent.children.index(@item)-1]
      parent.insert_before(before, @item)
    end

    respond_to do |format|
      format.html { redirect_to Item.find(@item.parent)}
    end
  end

  def move_down
    parent = Item.find(@item.parent)

    if parent.children.index(@item)+1 < parent.children.count
      after = parent.children[parent.children.index(@item)+1]
      parent.insert_after(after, @item)
    end

    respond_to do |format|
      format.html { redirect_to Item.find(@item.parent)}
    end
  end

  def destroy
    @item.children.each do |child|
      child.destroy
    end
    parent = Item.find(@item.parent)
    @item.destroy


    respond_to do |format|
      if @item.parent
        format.html  { redirect_to parent }
      else
        format.html  { redirect_to :back }
      end
    end
  end

  private
  def set_item
    @item = Item.find(params[:id])
  end

  def check_authN
      redirect_to root_path, notice: 'Please login first' unless current_user
  end

  def check_authZ
    if @item
      redirect_to root_path, notice: 'You are not authorized to do that' unless @item.user_id == current_user.id.to_s
    end
  end
end

app/views/item/edit.html.erb
<h1><%= f.text_field :title, :value=>@item.title, :autofocus => true, :class=>'form-control' %></h1>

  <div class="form-group">
    <%= f.datetime_local_field :duedate, :value=>@item.duedate, :autofocus => true, :class=>'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.text_field :notes, :placeholder=>'Add notes here', :value=>@item.notes, :autofocus => true, :class=>'form-control' %>
  </div>

app/views/item/index.html.erb
<h1>All Lists</h1>

<%= link_to "New List", new_item_path %>

<% if @items.count > 0 %>
  <ul class="list-group">
    <% @items.each do |item| %>
    <li class='list-group-item'>
      <%= link_to raw('<span class="glyphicon glyphicon-remove-sign pull-right"></span>'), item, method: :delete, data: { confirm: 'Are you sure? This will destroy all items in the list as well.' }, :class=>'text-danger' %>
      <%= link_to "#{item.title} - #{pluralize(item.children.count, 'item')}", item %>
      </li>
  <% end %>
  </ul>
<% end %>

app/views/item/index.json.erb
<%= raw(@items.to_json) %>

app/views/item/new.html.erb
<%= form_for(@item) do |f| %>

<h1>
    <%= f.text_field :title, :placeholder=>'New List Name', :autofocus => true, :class=>'form-control input-lg' %>
</h1>


<div class="form-group">
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  
  <div class="actions">
    <%= f.submit :class =>'btn btn-default', :value=>'Create List' %>
  </div>
</div>
<% end %>

app/views/item/show.html.erb
<h1><%= @item.title %></h1>

<div class='results'></div>

<%= form_for @item, :url => create_item_path, :html => {:method => :post} do |f| %>
<div class="form-group">
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :title, :placeholder=>'New Item (press enter to add)', :value=>'', :autofocus => true, :class=>'form-control input-lg' %>
  </div>
  
  <%= f.hidden_field :parent, :value => params[:id] %>
</div>
<% end %>

<% if @item.children.any? %>
  <ul class="list-group">
    <% pretty_id = 1 %>
    <% @item.children.each do |item| %>

    <li class="list-group-item">
        <%= link_to raw('<span class="glyphicon glyphicon-remove-sign pull-right"></span>'), item,  method: :delete, :class=>'text-danger' %>
        <%if pretty_id == 1%>
          <span class="glyphicon glyphicon glyphicon-chevron-up pull-right text-muted">&nbsp;</span>
        <% else %>
        <%= link_to raw('<span class="glyphicon glyphicon glyphicon-chevron-up pull-right">&nbsp;</span>'), move_item_up_path(item) %> 
        <% end %>
        <%if pretty_id == @item.children.count %>
          <span class="glyphicon glyphicon glyphicon-chevron-down pull-right text-muted">&nbsp;</span>
        <% else %>
        <%= link_to raw('<span class="glyphicon glyphicon glyphicon-chevron-down pull-right">&nbsp;</span>'), move_item_down_path(item) %>
        <% end %>

        <%= check_box_tag 'done', item.id , item.done, :class => "item-check" %>
        <%= pretty_id %>.) <strong><%= content_tag :span, item.title %></strong> (CO: <%= content_tag :span, item.order %>)

    </li>
    <% pretty_id += 1 %>
  <% end %>
  </ul>
  <% else %>
  No Items Yet
<% end %>

app/views/item/show.json.erb
<%= raw(@json) %>

app/views/item/toggle.html.erb
<h1>hello world</h1>